### ISSUE TITLE
It's not work

### ISSUE THREAD

**Issue by zhixuan666** [rtindru/colabAlive#4]
```
TypeError: Cannot read property 'click' of null
    at ligboxConnect (inject.js:28)
```

**Comment by sobuj53** [comment]
Take a look at, [new method for clicking button](https://github.com/rtindru/colabAlive/pull/5/commits/0dfc443a1a7ce3791c6f4f38dfd66e870c0e713a) . It's working for me.

**Comment by zhixuan666** [comment]
Thank you. It's running
